.TH safe-crux 1 LOCAL

.SH NAME

safe-crux - Safe CRUX Environment

.SH SYNOPSIS

.B safe-crux
.RB subcommand
.RB <arguments>

.SH SUBCOMMANDS

.TP 22
.B help
Show help information
.TP 22
.B version
Show version information
.TP 22
.B stat
Show status for mounted images
.TP 8
.B install
.IR <target|file>
Create new environment
.TP 8
.B use
.IR [target|file]
Use target or file as the environment
.TP 8
.B mount
.IR [target|file]
Mount the selected target or file as the environment
.TP 8
.B umount
.IR [target|file]
Umount the selected target or file as the environment

.SH AVAILABILITY

All Linux flavours

.SH AUTHORS

Jose V Beneyo, <sepen@crux.nu> 
.br
Victor Martinez, <pitillo@ono.com>
