#!/usr/bin/env bash

export SCX_SETUP_YES=0
export SCX_SETUP_TYPE="file"

scxSetupHelp() {
    cat << __EOF__
Usage: $SCX_APPNAME setup [option(s)] CRUX_VERSION TARGET

Options:

  -h       Print usage and quit
  -y       Assume "yes" as answer to all prompts
  -l       Print available CRUX_VERSION setup files
  -t TYPE  Target type (options: dir, block and file)

Examples:

  $SCX_APPNAME setup -t file  x86_64-3.5 /tmp/crux-x86_64.img
  $SCX_APPNAME setup -t dir   x86_64-3.5 /tmp/crux-x86_64
  $SCX_APPNAME setup -t block x86_64-3.5 /dev/sdb1
__EOF__
    exit 0
}

scxSetupList() {
    find "$SCX_SCXDIR" -maxdepth 1 -mindepth 1 -exec basename {} \; | sort -n
    exit 0
}

scxSetupLoadVersion() {
    local scx_version="$1"
    [ -f "$SCX_SCXDIR/$scx_version" ] || msgError "$scx_version not found, type -l for a list of available versions"
    # TODO: check if required vars and functions are available or show error
    source "$SCX_SCXDIR/$scx_version"
}

scxSetupPrepareIso() {
    local cmd_wget="wget -c -t 3 --waitretry=3 -P $SCX_ISODIR"
    local cmd_md5sum="md5sum"
    local iso_uri="$1"
    local iso_md5="$2"
    local iso_file="${iso_uri##*/}"
    local iso_md5file="${iso_md5##*/}"
    # TODO: check if wget command is available
    # download files
    # TODO: refactor to downloadFile function
    if [ ! -f "$SCX_ISODIR/$iso_file" ]; then
      msgInfo "Downloading ISO file from $iso_uri"
      $cmd_wget $iso_uri
    fi
    if [ ! -f "$SCX_ISODIR/$iso_md5file" ]; then
      msgInfo "Downloading MD5 file from $iso_md5"
      $cmd_wget $iso_md5
    fi
    [ ! -f "$SCX_ISODIR/$iso_file" ] && exit 1
    [ ! -f "$SCX_ISODIR/$iso_md5file" ] && exit 1
    # check md5sum
    cd $SCX_ISODIR && md5sum -c "$iso_md5file" || exit 1
    # mount iso
    mkdir -p $SCX_ISODIR/mnt
    sudo mount -o loop,ro -t iso9660 $SCX_ISODIR/$iso_file $SCX_ISODIR/mnt
}

scxSetupLeaveIso() {
    sudo umount $SCX_ISODIR/mnt >/dev/null 2>&1
}

scxSetupPrepareTarget() {
    local target="$1"
    # TODO: remove hardcoded vars from here
    local image_size="1024"
    local image_fstype="ext2"
    case "$SCX_SETUP_TYPE" in
        dir)
            [ ! -d "$target" ] && mkdir -p "$target"
            SCX_MNTDIR="$target"
            ;;
        block)
            sudo mount "$target" "$SCX_MNTDIR"
            ;;
        file)
            # TODO: refactor as makeImageFile
            if [ ! -f "$target" ]; then
                echo "makeImageFile size: $image_size MB"
                if [ -f $target ] && [ $SCX_SETUP_YES -eq 0 ]; then
                    read -p "File $target found, do you want to remove it [y|n] " response
                    [ "$response" = "y" ] && rm -vf $target
                fi
                sudo dd if=/dev/zero of=$target bs=1M count=$image_size
            fi
            sudo mkfs -F -t $image_fstype -q $target || exit 0
            sudo mount -o loop,rw "$target" "$SCX_MNTDIR"
            ;;
        *)
            scxSetupHelp
            ;;
    esac
}

scxSetupLeaveTarget() {
    sudo umount $SCX_MNTDIR >/dev/null 2>&1
}

scxSetup() {
    local tmpdir="$(mktemp -d)"
    local setup_version= setup_target=
    [ $# -eq 0 ] && scxSetupHelp
    while getopts :hylt: opt; do
        case "$opt" in
            h) scxSetupHelp ;;
            y) SCX_SETUP_YES=1 ;;
            l) scxSetupList ;;
            t) SCX_SETUP_TYPE="$OPTARG"; shift $((OPTIND-1)) ;;
        esac
    done
    # to continue we need at least 2 args
    [ $# -lt 2 ] && scxSetupHelp
    setup_version="$1"
    setup_target="$2"
    scxSetupLoadVersion "$setup_version"
    scxSetupPrepareIso "$scx_uri" "$scx_md5"
    scxSetupPrepareTarget "$setup_target"
    if [ $SCX_SETUP_YES -eq 0 ]; then
      echo "You will setup $setup_version on $SCX_MNTDIR"
      read -p "Continue? [y|N] " response
      [ "$response" != "y" ] && exit 0
    fi
    cd $tmpdir
    msgInfo "Running setup: $setup_target $setup_version"
    msgInfo "Please wait ..."
    scx-setup
    sudo rm -rf $tmpdir
    scxSetupLeaveIso
    scxSetupLeaveTarget
}
